#!/usr/bin/env node

import fs from "fs";
import path from "path";

function run() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (command === "generate") {
    console.log("Light ORM CLI - Schema Generation");
    
    // In a full version, this would compile the user's `models.ts` and inspect the runtime schema object.
    // For this lightweight version, we will scaffold a basic schema.sql file.
    
    const outputPath = path.join(process.cwd(), "db", "schema.sql");
    const outputDir = path.dirname(outputPath);
    
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const template = `-- Generated by Light ORM CLI
CREATE TABLE IF NOT EXISTS public.users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`;
    
    fs.writeFileSync(outputPath, template);
    console.log(`✅ Schema generated at ${outputPath}`);
  } else {
    console.log("Usage: light-orm generate");
  }
}

run();
